name: Update M3U Playlist

on:
  schedule:
    - cron: '*/30 * * * *' # Chạy mỗi 30 phút
  workflow_dispatch: # Cho phép bấm chạy thủ công

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python bot.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Lấy dữ liệu mới nhất về để tránh xung đột
          git pull origin main --rebase
          
          # Kiểm tra xem có thay đổi gì không trước khi commit
          git add playlist.m3u
          if git diff --staged --quiet; then
            echo "Không có thay đổi nào trong playlist."
          else
            git commit -m "Update playlist $(date +'%Y-%m-%d %H:%M')"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
          fi
