name: Update M3U Playlist

on:
  schedule:
    - cron: '*/10 * * * *' # Chạy mỗi 10 phút
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python bot.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git fetch origin main
          git reset --soft origin/main
          
          # SỬA TẠI ĐÂY: Thêm tất cả các file có đuôi .m3u (bao gồm cả playlist và vongcam)
          git add *.m3u
          
          # Kiểm tra nếu có bất kỳ file m3u nào thay đổi thì mới commit
          if git diff --staged --quiet; then
            echo "Không có trận đấu mới ở cả 2 nguồn, bỏ qua commit."
          else
            git commit -m "Update playlists (HoiQuan & Vongcam): $(date +'%d/%m/%Y %H:%M')"
            git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
          fi
