name: Update M3U Playlist

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python bot.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Buộc cập nhật dữ liệu từ GitHub về và ưu tiên bản trên Cloud
          git fetch origin main
          git reset --soft origin/main
          
          git add playlist.m3u
          
          # Chỉ push nếu có sự thay đổi thực sự trong file playlist
          if git diff --staged --quiet; then
            echo "Không có trận đấu mới, bỏ qua commit."
          else
            git commit -m "Update playlist: $(date +'%d/%m/%Y %H:%M')"
            git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
          fi
